---
server_blocks:
  - server_name: coding1.dciets.com
    proxy_pass: http://127.0.0.1:4000
    logfile_name: coding1

  - server_name: darksouls.dciets.com
    proxy_pass: http://127.0.0.1:6001
    logfile_name: darksouls

  - server_name: emailtemplates.dciets.com
    proxy_pass: http://127.0.0.1:6002
    logfile_name: emailtemplates

  - server_name: fouraide.dciets.com
    proxy_pass: http://127.0.0.1:6003
    logfile_name: fouraide
    ws: true

  - server_name: sqlibasic.dciets.com
    proxy_pass: http://127.0.0.1:10000
    logfile_name: sqlibasic

  - server_name: sqlifilters.dciets.com
    proxy_pass: http://127.0.0.1:10001
    logfile_name: sqlifilters

  - server_name: spammy.dciets.com
    proxy_pass: http://127.0.0.1:10002
    logfile_name: spammy

  - server_name: flagbook.dciets.com
    proxy_pass: http://127.0.0.1:10003
    logfile_name: flagbook
