---
- name: apt-get update
  apt:
    update_cache: yes

- name: Install htop
  apt:
    name: htop
    state: present

- name: Install vim
  apt:
    name: vim
    state: present

- name: Install pip
  apt:
    name: python-pip
    state: latest

- name: Install Python3
  apt:
    name: python3
    state: latest
