---
- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Add the GPG key for the Debian Docker repository
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add the Docker Ubuntu repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    state: present
    update_cache: yes

- name: Install Docker
  package:
    name: docker-ce
    state: latest

- name: Start docker service
  service:
    name: docker
    enabled: yes
    state: started

- name: Install docker-compose
  pip:
    name: docker-compose
