---
- name: kill all running challenges
  shell: docker kill $(docker ps -q)
  tags: ['never', 'kill_challenges']

- name: build challenge images
  tags: build
  docker_image:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
    force: true
  with_items:
    - "{{ challenges }}"

- name: run challenge images
  tags: run
  docker_container:
    name: "{{ item.name }}"
    image: "{{ item.name }}"
    restart: yes
    ports:
      - "{{ item.ports }}"
  with_items:
    - "{{ challenges }}"

- name: build mysql_challenges
  command: "./start.sh chdir=/opt/dci-ctf-2018/challenges/web/mysql_challenges"
  when: (challenge == "mysql_challenges") or challenge is not defined
