---
- name: Build coding1
  docker_image:
    name: coding1
    path: '/opt/dci-ctf-2018/challenges/coding/coding1'
    force: true
  tags:
    - coding
    - coding1

- name: Start coding1
  docker_container:
    name: coding1
    image: coding1
    restart: yes
    ports:
      - "0.0.0.0:5001:5001"
  tags:
    - coding
    - coding1
